### PR TITLE
Fixed error in german.js, added code to main.js to check for blank te…

### PR DESCRIPTION
**Pull request by scottpschaffer**
In main.js, I moved the If-Else into another if-else that checked for empty TextArea and made Key words capitalized in russian.js.

### CODE REVIEW

**Comment by madduxTim** [comment]
:+1:

**Comment by morecallan** [comment]
:+1: Looks stellar!

**Comment by ZachParris** [comment]
:+1:

**Comment by madduxTim** [comment]
merging on Scott's behalf.

**Pull request merged**
